// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAguNeSxcKg3Sjj5ThwOQi_qEJmL4pg5Ds',
    appId: '1:697886710494:web:5d0ea98537450b0ac3004f',
    messagingSenderId: '697886710494',
    projectId: 'fixit-1b8b8',
    authDomain: 'fixit-1b8b8.firebaseapp.com',
    storageBucket: 'fixit-1b8b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIL2QGPyrbqyCXF9sCP_m0lrhvr6gK2oM',
    appId: '1:697886710494:android:bd3e569feffc50c0c3004f',
    messagingSenderId: '697886710494',
    projectId: 'fixit-1b8b8',
    storageBucket: 'fixit-1b8b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3okkw7inMzstvN5qY1jXBNsJ7VLW03po',
    appId: '1:697886710494:ios:0796b228fa29a437c3004f',
    messagingSenderId: '697886710494',
    projectId: 'fixit-1b8b8',
    storageBucket: 'fixit-1b8b8.appspot.com',
    androidClientId: '697886710494-v1n279dao765l9fntavts7492j68b2mq.apps.googleusercontent.com',
    iosClientId: '697886710494-knaod1tf15um5d64ui4106mr14t1judo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3okkw7inMzstvN5qY1jXBNsJ7VLW03po',
    appId: '1:697886710494:ios:0796b228fa29a437c3004f',
    messagingSenderId: '697886710494',
    projectId: 'fixit-1b8b8',
    storageBucket: 'fixit-1b8b8.appspot.com',
    androidClientId: '697886710494-v1n279dao765l9fntavts7492j68b2mq.apps.googleusercontent.com',
    iosClientId: '697886710494-knaod1tf15um5d64ui4106mr14t1judo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixitProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAguNeSxcKg3Sjj5ThwOQi_qEJmL4pg5Ds',
    appId: '1:697886710494:web:13430b7972078ca3c3004f',
    messagingSenderId: '697886710494',
    projectId: 'fixit-1b8b8',
    authDomain: 'fixit-1b8b8.firebaseapp.com',
    storageBucket: 'fixit-1b8b8.appspot.com',
  );
}
